spring:
    #rabbitmq 开发环境
   rabbitmq:
    host: 192.168.2.8
    port: 5672
    username: admin
    password: admin123
    virtual-host: /
   jpa:
    database: MYSQL
   #master数据库 开发环境
   datasource:
   # 下面为连接池的补充设置，应用到上面所有数据源中
      type: com.alibaba.druid.pool.DruidDataSource
# 初始化大小，最小，最大
      initialSize: 10
      minIdle: 10
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小 如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false。
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 stat,wall,log4j2,slf4j
      filters: wall,stat,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      driver-class-name:  com.mysql.jdbc.Driver

   master:
      datasource:
          username: root
          password: 123456
          url: jdbc:mysql://localhost:3306/%s?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
   #slave数据库 开发环境
   slave:
      datasource:
          username: root
          password: 123456
          url: jdbc:mysql://localhost:3306/%s?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
  #redis 配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: yst904530
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 300
    # 连接池最大阻塞等待时间（使用负值表示没有限制-1）
    max-wait: 10000
    # 连接池中的最大空闲连接
    max-idle: 100
    # 连接池中的最小空闲连接
    min-idle: 0
    # 连接超时时间（毫秒）
    timeout:  0