#redis 配置
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: yst904530
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 300
    # 连接池最大阻塞等待时间（使用负值表示没有限制-1）
    max-wait: 10000
    # 连接池中的最大空闲连接
    max-idle: 100
    # 连接池中的最小空闲连接
    min-idle: 0
    # 连接超时时间（毫秒）
    timeout:  0